### ISSUE TITLE
500 response when trying to sign up for a staging.chitchats account

### ISSUE THREAD

**Issue by Braedencraig** [chitchats/chitchats-api-doc#25] opened 2021-01-02 19:30 UTC
When i'm trying to sign up for a staging account, I get a 500 error but am not seeing any issues reported. Anyone else experiencing this?

**Comment by sukh-gill** [comment] 2021-01-03 00:51
Having the same issue.

**Comment by wesbos** [comment] 2021-01-04 01:37
Same here, I sent in a support request but didn't hear back yet. Started happening early January 1st for me. 

The chit-chats staging dashboard also creates this issue. It can be replicated with:

```bash
curl --request POST \
  --url https://staging.chitchats.com/api/v1/clients/XXX/shipments \
  --header 'Authorization: XXX' \
  --header 'Content-Type: application/json' \
  --data '{
        "name": "wes bos",
        "address_1": "1201 Wayne Ave",
        "address_2": "",
        "city": "Dayton",
        "province_code": "OH",
        "postal_code": "45410",
        "phone": "4168333641",
        "country_code": "US",
        "description": "Pink on Pink tshirt",
        "value": "34",
        "value_currency": "usd",
        "package_type": "parcel",
        "package_contents": "merchandise",
        "size_unit": "cm",
        "size_x": 17,
        "size_y": 5,
        "size_z": 23,
        "weight_unit": "g",
        "weight": 215,
        "ship_date": "today",
        "postage_type": "unknown"
}'
```

The returned value is always:

```
{"error":{"message":"Internal Server Error","reference":"86c8580d"}}%                          
```

**Comment by wesbos** [comment] 2021-01-04 01:40
Just re-read your issue in that you can't sign up. This is with creating shipments. You can list existing ones, but not create new ones. Seems like a large portion of the API is down. 

Nothing here - https://status.chitchats.com/

**Comment by gshaw** [comment] 2021-01-04 06:47
Thanks for reporting this.  Our staging will sometimes go off-line or be unavailable for short periods but this was caused by the us miss creating a staging partition on for 2021 before Jan 1 arrived. I did a quick check and I think it's working but if not we'll have this fixed on Monday.

If anybody can confirm/deny the problem is still happening that would help.

**Comment by wesbos** [comment] 2021-01-04 14:08
It's working again! Thanks @gshaw - I hope we didn't bug you on your last day of vacation. 

This issue can be closed

**Closed** 2021-01-04 19:02 UTC

**Comment by Braedencraig** [comment] 2021-01-04 23:16
Thank you soooooooo much @gshaw !

**Comment by gshaw** [comment] 2021-01-06 05:58
@Braedencraig please thank me when I roll out a new feature instead of fixing something we broke 🙃
